### ISSUE TITLE
JumpscaleLib/clients/zdb needs to work for usermode aswell

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscale_lib#1]
/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/zdb/ZDBClientNS.py

- need to fix for direct mode
- need tests for direct mode

**Comment by despiegk** [comment]
also make tests for sequential ok

**Comment by despiegk** [comment]
direct mode indeed dropped

**Comment by rkhamis** [comment]
so I can close this? @despiegk @maxux

**Comment by zaibon** [comment]
been playing with user mode yesterday and fixed what I found was not working in https://github.com/threefoldtech/jumpscale_lib/commit/9999cdd232478842379adb4e56b0a602fb58197e

I'll close
