### ISSUE TITLE
RivineClient: Run check address in parallel

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#12]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/361](), opened by @ahussein*

At the moment when checking the current balance, the code would check all the addresses of a the wallet by making REST API calls to the explorer node. This check is now done sequentially for each address, while this should be okay for small number of address, it will be slow for a larger number and specially if the network has some latency.

The purpose of this task is to modify the code [here](https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/blockchain/rivine/RivineWallet.py#L152) and [here](https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/blockchain/rivine/RivineMultiSigWallet.py#L137) to allow the collection of addresses information to run in parallel.

**Comment by despiegk** [comment]
still relevant?

**Comment by ahussein** [comment]
Yes it is still relevant. It will help speed up the current balance inquiry when using the light wallet.
