### ISSUE TITLE
ZOS SAL: node.public_address can return wrong ip if support flag is enabled

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscale_lib#121]
When the public_address method has been written we used to only ever have one single zerotier interface on the host and we use the ip of this interface to fill the public_address of the node:

https://github.com/threefoldtech/jumpscale_lib/blob/89acbbd28694ea1a576bc7a7783fd8ef4804dc41/JumpscaleLib/sal_zos/node/Node.py#L105-L112

Now that we have the support flag that also create a zerotier interface at boot. This code is non deterministic and can return the support ip or the management ip.

I propose we change the code to:
- exclude the range of the support network (172.29.0.0/16) from the `public_address` property code
- add another property `support_address` to the Node class and return the ip of the support zerotier interface if any
- add a `management_address` that will just return the same ip as the public address. This is to start  migration from `public_address` to `management_address` in the code. cause public address is not really a proper name for it.

**Comment by delandtj** [comment]
support=ztid as kernel parameter would be even better, as different groups might want to define their own support

**Comment by zaibon** [comment]
> support=ztid as kernel parameter would be even better, as different groups might want to define their own support

this is out of scope for this issue. If you want that feature create an issue on https://github.com/threefoldtech/0-core/issues

**Comment by zaibon** [comment]
@BolaNasr let's try to get this out of the way today please. Thx

**Comment by zaibon** [comment]
very nice, thanks @BolaNasr
