### ISSUE TITLE
Refactor capacity tracking code to something more simple

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscale_lib#122]
Currently we use pretty complex flow to gather the raw resources of a machine: dmidecode, smartctl,...
This has been done like this cause we wanted to be able to gather unique identification code from the hardware. It turns out that we can't rely on those. So there is not point using dmidecode or smarctl at all.
We could have a much simpler code that just use the ZOS primitives to get the raw capacity.
This would make the code more compatible with more hardware since we would only use generic linux interface to read the data out of the system.

Practically the code in https://github.com/threefoldtech/jumpscale_lib/blob/development/JumpscaleLib/sal_zos/capacity/Capacity.py needs to be refactor to only use the zos primitives and drop usage of dmidecode and smartctl.

child of #120

**Comment by delandtj** [comment]
hmmm... standard linux primitives don't have the same leven of deep inspection as dmidecode and/or smartctl... I think

**Comment by maxux** [comment]
Update: since 8da1d1ea0980c0da1493dc37ae3969e60137031e, the code was refactored and simplified a lot. This is in testing stage.

**Comment by hossnys** [comment]
if here is the right issue to put this comment ,, the capacity grid don't show the updated total report of storage (i.e : CRU ) when removing a physical disk from node .
like here from the capacity client of node :

```
In [17]: node.capacity.total_report()
Out[17]: {"mru": 7.83, "hru": 1863.03, "cru": 4, "sru": 29.8}
```
and here is what shown on site : 

![screenshot from 2018-11-25 18-22-15](https://user-images.githubusercontent.com/26298009/48981618-8e90e080-f0e0-11e8-8bd2-b814965d3883.png)
