### ISSUE TITLE
Improve rivine multisig wallet

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/jumpscale_lib#125]
Currently it can only create transactions which send to a regular address. It should also be able to send to other multisig addresses. Furthermore, it seems that there is no logic which handles refunds, meaning you must spend every input used in the transaction either by sending it or by using it as minerfee, which would often be undesired

**Comment by robvanmieghem** [comment]
I actually  think the way multisig is implemented in jumpscale is very complex since you have to create a multisig wallet.
