### ISSUE TITLE
remove restic support from minio sal

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscale_lib#126]
We are not going to use restic to save the metadata of the minio anymore, so we can remove any logic related to restic from the minio SAL

**Comment by BolaNasr** [comment]
https://github.com/threefoldtech/jumpscale_lib/commit/d6310d9a1151abbbf4f3876b12ffcb7f84d36b08
https://github.com/threefoldtech/0-templates/commit/8ebd80a8474ffd65b5c077b5c27b2a947404d26c

**Comment by Dina-Abd-Elrahman** [comment]
## jumpscale version:

core : 28515efa893162cfc08cc4e259bc268a4c48ef4d
lib : 2b368d2328a63d04ab126fec36ca307bd0ebebba
prefab : 44e92d0c9e47f663c1ede06e8d8c983905da581d
