### ISSUE TITLE
RivineClient: Improve the quality of the code

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#13]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/360](), opened by @ahussein*

While working on https://github.com/Jumpscale/lib9/issues/353 . Multiple problems with the current structure and codebase of the Rivine client code showed up.
The code contains some code duplication and the structure forced creating more duplicate code to make the multisig feature work.

The purpose of this task is to review the current code base and restructure when possible to eliminate code duplication and allow the code to be extensible with more features in the future.

**Comment by despiegk** [comment]
whats state, how urgent, what do we want to do?
how much work?
need to see after this if we do this story in the sprint for9.5.1

**Comment by ahussein** [comment]
This will take a couple of days work.
The current client code has some duplication and the structure need to be improved to make it easy to support additional features from the Rivine daemon.

It is not urgent but I would recommend to work on this as soon as someone has some free time.

**Comment by ahussein** [comment]
closing this issue. The code was reviewed and improvement tasks were created by @GlenDC
