### ISSUE TITLE
We need more information about gateway network options

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscale_lib#138]
According to the GW docs https://github.com/threefoldtech/jumpscale_lib/blob/development/docs/SAL/zos/0-gateway-examples.md  , We can create a GW with public nw which is  in `['default', 'pathrought', 'bridge','vlan','vxlan']` and with private nw which is in `['zt', 'vlan', 'vxlan']` but we dont know what is the physical nw requirements to use each one of those nw configuration.

So for each nw option we need to knw what exactly the use case of it.

**Comment by zaibon** [comment]
gateway is not going to be used as it is presented here.
