### ISSUE TITLE
Updating vm disk after deploying vm result error 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#141]
#### Installation information

- jumpscale version: development
- jumpscale_lib : commit e6f7728a1b8a6639f785f9d1d76cd36afdf15f31
- operating system: Ubuntu 18

#### Detailed description
1- create zdb 
2- add namespace to zdb
3- get information about zdb using zdb object
4- get information about the same zdb using node.zerodb.list
5- create vdisk using zdb and namespace
6- create ubuntu vm
7- add zerotier to vm networks
8- deploy vm 
9- attach vdisk to vm disks 
10- update vm disk

#### Steps to reproduce
```
zdb = node_sal.primitives.create_zerodb(node_port=9901, name='test_zdb', path='/mnt/zdbs/sda', mode='user', sync=False, admin='mypassword')
zdb.deploy()
zdb.namespaces.add('test_ns', size=5)
zdb.to_dict()
zdb_from_list = node_sal.zerodbs.list()[0]
zdb_from_list.to_dict()
disk = node_sal.primitives.create_disk('test_ns', zdb=zdb, size=5)
disk.deploy()
vm = node_sal.primitives.create_virtual_machine('test_vm', type_='ubuntu:16.04') 
zt_client = j.clients.zerotier.get(data={'token_': <zt_token>})
zt_network = zt_client.network_get(<zt_id>)
vm.nics.add_zerotier(zt_network)
vm.deploy()
vm.disks.add(disk)
vm.update_disks()
```
### Actual Result
- info about zdb from list don't retrieve the same info the object has (drop namespace)
![list_zdb](https://user-images.githubusercontent.com/41957921/45753633-bc0d6980-bc19-11e8-81bf-9b1fcfe7ece4.png)

- update vm disk after deploying vm result error, although if i attach the disk before deploying vm works.
![image](https://user-images.githubusercontent.com/41957921/45754101-fd524900-bc1a-11e8-9327-1c85251c464a.png)

**Comment by zaibon** [comment]
closed for inactivity
