### ISSUE TITLE
Create zdb with same name  and different port 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscale_lib#143]
Create zdb with same name like another created zdb name but with different name , then deploy it , it will stuck and after long time will result runtime error  
```
ConnectionError: Error 110 connecting to 172.22.247.140:2253. Connection timed out.
```
## creation of zdb 
```
zd = node.primitives.create_zerodb("test5",node_port=223, path='/mnt/zdbs/sdc')
zd.deploy()
```

**Comment by zaibon** [comment]
>Create zdb with same name like another created zdb name but with different name 

@Dina-Abd-Elrahman can you clarify cause this sentence does not really make sense

**Comment by Dinaamagdy** [comment]
@zaibon  I mean  different zdb port not name but as I see now there isn't node_port parameter so I will close this issue
