### ISSUE TITLE
Adding namespace to zdb with size more than disk size 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#144]
#### Installation information

- jumpscale version: development
- jumpscale_lib : commit 9353fa35240a04ee204d3e6e19ba717a099dde51
- operating system: Ubuntu 18

#### Detailed description
1- create zdb.
2- add namespace to zdb with size more than disk size.
3- deploy zdb.

#### Steps:
```
from jumpscale import j
node_sal = j.clients.zos.get(data={'host': <node_ip>})
zdb = node_sal.primitives.create_zerodb(node_port=9901, name='test_zdb', path='/mnt/zdbs/sda', mode='user', sync=False, admin='mypassword')
zdb.namespaces.add('myns1',size=200)
zdb.deploy()
zdb.info
```
### Actual Result

The zdb deployed with this namespace.
zdb.info had negative free space !!

![image](https://user-images.githubusercontent.com/41957921/45823503-2099f880-bcee-11e8-8fdd-2b58b11c74c6.png)

**Comment by zaibon** [comment]
closed for inactivity
