### ISSUE TITLE
support registration of a 3bot using the tfchain client

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscale_lib#149]
It should be possible to:

* register a 3bot using the JS tfchain client;
* fetch the information of a 3bot based on its ID or Public Key;
* be able to update the record of a registered 3bot;
* be able to transfer one or multiple names from one 3bot to another;

Note that a 3bot requires a wallet as well, doesn't have to be a wallet owned by the 3bot, but the caller registering the 3bot (and/or updating its information) does not funds in an owned wallet as to be able to fund the necessary liquid coin outputs as coin inputs.

A 3bot can be registered as well as updated after registration. A 3bot cannot be deleted, but you can deactivate (meaning no network addresses are registered any longer) it by updating it in a specific way. A 3bot can own one or multiple names (work similar to how DNS names work). Should a 3bot want, it can transfer one or multiple names (it owns) to another 3bot. All these actions (registrations, updates and transfers) can be done by creating and sending the new transaction types: <https://github.com/threefoldfoundation/tfchain/blob/master/specs/3bot_registration.md#transactions>. Information about the properties and the structure of the Tx types can be found here as well.

The record (including its unique ID) of a 3bot can be retrieved using either its public key (`string`) or its unique ID (`uint32`), using the new Explorer endpoint `GET /explorer/3bot/:id` (where `:id` is either the public key or unique ID). More information can be found at <https://github.com/threefoldfoundation/tfchain/blob/master/specs/3bot_registration.md#get-explorer3botid>. Information about the return object and its properties can be found here as well.

For more information, you can find everything in the complete and detailed technical spec of this feature: <https://github.com/threefoldfoundation/tfchain/blob/master/specs/3bot_registration.md>

Note that it is not yet deployed to [tfchain][tfchain]'s testnet. You'll have to setup your own devnet by spawning one or multiple nodes using the `--network devnet` flag. With the `--no-bootstrap` flag, and manually connecting the nodes using `tfchainc gateway connect` should you use multiple nodes (not required for this feature).

[tfchain]: http://github.com/threefoldfoundation/tfchain

**Comment by GlenDC** [comment]
Once it is unblocked, someone will have to decide on the priority level of it, I have no clue about that.

**Comment by GlenDC** [comment]
Related [tfchain][tfchain] issues:

* <https://github.com/threefoldfoundation/tfchain/issues/189>;
* <https://github.com/threefoldfoundation/tfchain/issues/190>;

[tfchain]: https://github.com/threefoldfoundation/tfchain

**Comment by GlenDC** [comment]
As preparation for the 3bot support in JS, the `tfchain` library can be extended to support some of the new binary encoding algorithms as described in https://github.com/threefoldtech/jumpscale_lib/issues/187, which should be already enough work to get started, while the rest of this story card is slowly but sure getting unblocked as well.

**Comment by GlenDC** [comment]
On the [tfchain '3bot-registration' branch](https://github.com/threefoldfoundation/tfchain/tree/3bot-registration) you can get the `tfchainn` version which is feature-complete in terms of the 3bot-registration, since yesterday. Should be sufficient to already implement any support required on the JS side.

Creating transactions is done using the `transaction pool` endpoints, this hasn't changed. So once you support the new Transaction versions, actually creating them should be trivial. Working on the documentation ASAP, because some information is still missing (e.g. how to sign transactions), but beyond that all is good. 

The spec that for now is to be used as documentation can be found at <https://github.com/threefoldfoundation/tfchain/blob/352e949ce7521f90ddae85276b6428729a9e36a4/specs/3bot_registration.md>.

**Comment by GlenDC** [comment]
The 3Bot registration concept and its technical details, within the context of tfchain, is documented and available at <https://github.com/threefoldfoundation/tfchain/blob/3bot-registration/doc/3bot.md>.

The (tfchain) binary encoding lib is also documented at <https://github.com/threefoldfoundation/tfchain/blob/3bot-registration/doc/binary_encoding.md>.

And finally, the three different 3Bot transactions, to create and update records as well as transfer names between 3Bots, are documented at <https://github.com/threefoldfoundation/tfchain/blob/3bot-registration/doc/transactions.md#3bot-transactions>.

Should there be errors in the documentation, or should some documentation be missing, please let me know and I'll try to help where I can.

**Comment by GlenDC** [comment]
The tfchain repo now also has `light_wallet` documentation, which adds the information for tfchain-specific features as relevant for light (client) wallets. For the regular stuff it refers to the Rivine documentation, but does explain about the 3Bot features, so you know what (explorer) endpoints are available and to be used.

You can find this documentation at <https://github.com/threefoldfoundation/tfchain/blob/3bot-registration/doc/light_wallet.md#3bot>.

**Comment by zaibon** [comment]
If we have a `3bot` namespace on the tfchain already as show in `tfchain.3bot.get_record` shouldn't the creation and recover of a 3bot also be there ? Or is there technical reason we want to attach these method to the wallet ?

**Comment by GlenDC** [comment]
> If we have a `3bot` namespace on the tfchain already as show in `tfchain.3bot.get_record` shouldn't the creation and recover of a 3bot also be there...

First of all, it's the first time I'm designing within the JS space, so I might not follow its philosophy yet. All I know is that it should be as high level as possible, such that scripters can understand the command(s) to use very easily, without having to know how it works technically under the hood.

That being said...

The reason I attached it to the wallet is so that I can embed the wallet within a kind of `3bot` controller object, such that you can easily update it, without requiring to call a wallet separately. That's the technical reason, but even I question this design.

Getting a 3Bot record doesn't require a wallet, so we're fine there.

It gets trickier however when we want to register (create) or update (update/name-transfer) a 3Bot, as those require transactions, and thus fees to be paid (the regular Tx fee as well as the additional fees because of the 3Bot payment). Hence, we cannot simply have those as stand-alone functions.

We could of course have functions in the 3bot namespace, to create those Transactions, and than sign+commit them using the wallet, but I have a feeling that that would be seen as too low-level.

Either way, I'm completely open to suggestions from you @zaibon. You have plenty of experience in this space, so I'm all ears. Please do suggest, as I do question my current proposal as well.

**Comment by ahussein** [comment]
quick question:
- Isnt controller.update_record will eventually also creates a transaction ? why its called update record while the other API is called create_name_transfer_transaction? I would call it just controller.transfer_name instead.

**Comment by robvanmieghem** [comment]
I think putting all methods in the 3bot namespace makes more sense too but you are right about the querying, that does not need a wallet.
Also, I would merge the get_record and whois methods.

**Comment by GlenDC** [comment]
> Also, I would merge the get_record and whois methods.

Was thinking about that, only issue being that I would need to differentiate somehow between 2 cases, with 3 types of inputs. Will try to make it happen in a clean way.

**Comment by GlenDC** [comment]
> I would also simplify the api by not having create transaction methods and having to sign later but directly sign and commit.

I think there is a misunderstanding here. I only have one create function. That is for the name transfer method, as it requires signatures from 2 3bots.

The other transaction types have can and do sign and commit directly.

**Comment by GlenDC** [comment]
> Although ugly, we could create a small3bot namespace on the tfclientcontroller solely with the search method and maybe a get_3botcontroller method that needs a wallet as an argument .

What if all functions are in the 3bot namespace and require a wallet as first argument? Or would that be very anti-python?
