### ISSUE TITLE
Namespace properties is not updated after changing them

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#154]
#### Installation information

- jumpscale version: development
- jumpscale_lib : commit 9353fa35240a04ee204d3e6e19ba717a099dde51
- operating system: Ubuntu 18

#### Detailed description
1- create zdb 
2- add namespace 
3- change size of namespace or any property.
4- check namespace size
5- check namespace info

#### Steps to reproduce
```
node_sal = j.clients.zos.get(data={'host':<node ip>})
zdb = node_sal.primitives.create_zerodb(node_port=9901, name='test_zdb', path='/mnt/zdbs/sda', mode='user', sync=False, admin='mypassword')
ns = zdb.namespaces.add(name='test_ns', size=10)
zdb.deploy()
ns.set_property(prop='maxsize', value=444)
ns.info().to_dict()
ns.size
```

### Actual Result 
the size in ```ns.info().to_dict()``` is updated, but in ```ns.size ```is not updated.
![image](https://user-images.githubusercontent.com/41957921/46011075-03d23c00-c0c5-11e8-8982-8ae2243a8cb9.png)

![image](https://user-images.githubusercontent.com/41957921/46004317-df6d6400-c0b2-11e8-825c-135c505f00c4.png)

**Comment by zaibon** [comment]
closed for inactivity
