### ISSUE TITLE
Starting zero-db after stopping it, result error

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#159]
#### Installation information

- jumpscale version: development
- jumpscale_lib : commit 9353fa35240a04ee204d3e6e19ba717a099dde51
- operating system: Ubuntu 18

#### Detailed description
1- create zdb.
2- deploy it.
3- stop it.
4- start it.

#### Steps to reproduce
```
node_sal = j.clients.zos.get(data={'host':<node ip>})
zdb = node_sal.primitives.create_zerodb(node_port=9901, name='test_zdb', path='/mnt/zdbs/sda', mode='user', sync=False, admin='mypassword')
zdb.deploy()
zdb.stop()
zdb.start()
```
### Actual Result
After starting zdb again.

![image](https://user-images.githubusercontent.com/41957921/46086345-2be69b80-c1a8-11e8-9b20-3f7429a2f7ee.png)

**Comment by serboctor** [comment]
This will happen to all sals that stop the container in the `stop` function. I fixed it in this commit but the branch isn't merged yet. I'll set it to verification once the branch is merged.
https://github.com/threefoldtech/jumpscale_lib/commit/5f6f613819d5272e68eed4d64c0759e97658038d

**Comment by abdulgig** [comment]
Just verifying this on Ubuntu 18 , seems to be working correctly now

`In [6]: zdb = node_sal.primitives.create_zerodb( name='test_zdb', path='/mnt/zdbs/sda', mode='user', sync=False, admin='mypassword')

In [7]: zdb.deploy()
[Sun07 14:46] - zerodb.py         :243 :.sal_zos.zerodb.zerodb - INFO     - start zerodb test_zdb

In [8]: zdb.start()

In [9]: zdb.stop()

In [10]: zdb.start()
[Sun07 14:47] - zerodb.py         :243 :.sal_zos.zerodb.zerodb - INFO     - start zerodb test_zdb

In [13]: zdb.is_running()
Out[13]: True

`
![verify](https://user-images.githubusercontent.com/25789764/46581007-0a57a080-ca41-11e8-8115-5acf2aca07d5.png)

**Comment by AhmedHanafy725** [comment]
## Verified on 
js_core : 617a7ad5a767f1fd7fb7a2a5d6a8cc9c112009e8
js_lib: ea4504efd1755e3f710e0490e963b08ba1a234c8
