### ISSUE TITLE
Redeploying a zero-db after adding or removing network doesn't work

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#169]
#### Installation information

- jumpscale version: development
- jumpscale_lib: commit e7f8721a238e41e04854f5552be42144b957f256
- operating system: Ubuntu 18

#### Detailed description
1- create zdb.
2- deploy it.
3- add zerotier network to zdb 
4- redeploy.
5- remove zerotier network from zdb 
6- redeploy.

#### Steps to reproduce
```
node_sal = j.clients.zos.get(data={'host':<node ip>})
zdb = node_sal.primitives.create_zerodb(node_port=9901, name='test_zdb', path='/mnt/zdbs/sda', mode='user', sync=False, admin='mypassword')
zdb.deploy()
zt_client = j.clients.zerotier.get(data={'token_': <zt_token>})
zt_network = zt_client.network_get(<zt_id>)
zdb.nics.add_zerotier(zt_network)
zdb.deploy()
```
#### Actual Result
zdb didn't join zerotier network and didn't result error.
if zerotier network added before the first deploy, it would work.
but if i remove it and deploy again, zdb won't result error and it will be accessible through the zerotier network.

**Comment by zaibon** [comment]
closed for inactivity
