### ISSUE TITLE
Unconfirmed transactions are not shown in rivine wallet.current_balance

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscale_lib#181]
And rename simply to `balance`

**Comment by ahussein** [comment]
@robvanmieghem I am not sure what do you mean that its not shown.
Do you want the balance to show the following ? :
- Locked confirmed balance 
- Unlocked confirmed balance
- Locked unconfirmed balance
- Unlocked unconfirmed balance

**Comment by robvanmieghem** [comment]
Indeed, the same as now: unlocked, locked, multisig but  in a "unconfirmed" section
