### ISSUE TITLE
support tfchain-specific binary encoding logic in the JS tfchain lib

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscale_lib#187]
In order to be able to sign a transaction of any of the new 3bot transaction versions, support will be required for a subset of the new encoding features that are part of the official Go version of tfchain. As the JS tfchain lib requires the binary encoding only for signing only some features is required, and not all. Following is a list of what is required to be implemented.

### Integers

Dynamic byte-sized integers. In Rivine, binary encoding all integer types were binary encoded as 64bit unsigned integers using Little-Endianesses, and thus using 8 bytes. The tfchain encoding logic is a bit smarter here and only uses as much bytes as is required. This is possible, as the decoder knows what types to expect. All integers are still binary-encoded as unsigned integers using little-endianesses, but the amount of bytes uses is now different:

+ uint8, int8: 1 byte
+ uint16, int16: 2 bytes
+ uint24, int24: 3 bytes
+ uint32, int32: 4 bytes
+ uint64, int64, uint, int: 8 bytes

All integers in the new 3bot transaction versions are encoded using this scheme.

Relevant Go Unit Tests:
- a tiny example of a 24bit integer, as it is a bit of an odd thing: <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/encoding/int_test.go#L9-L28>;
- tests valid cases, to ensure we can execute a marshal-unmarshal cycle, as well as to ensure the byte length of the marshalled value is as expected: <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/encoding/encode_decode_test.go#L25-L255> (ignore the alias cases in this test, that is a "Go" problem, not something i think you'll have to deal with in Python);
- tests invalid cases: <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/encoding/encode_decode_test.go#L257-L541>;

### Slices

In Rivine, binary-encodes all slices with an 8-byte (uint64) Little-Endian binary encoded integer, indicating the length of the slice. All elements are encoded afterwards one by one, in the order as given. Should the slice be empty, the only thing encoded would be that length prefix, of all zeros (8 of them). This was a waste of space for 2 reasons:

+ Rivine did but a limit on many slice elements are allowed, `5e6`. The encoding logic (in Go) panics if more than that amount of elements are in a slice to be decoded or encoded. Given this limit, it is weird that the choice was made for a 64bit uint, rather than a 32bit uint, given that the latter still easily fits that limit;
+ Even the 4 bytes saved, by choosing a 32bit uint as length, would still be a waste of space for most slices. Most slices have less than 128 elements, which easily fit in a 1 byte length prefix, giving a 7 byte save per slice for such (most common) slices;

In tfchain slices are allowed a length prefix of 1, 2, 3 or 4 bytes. It can do so by using the following logic flow:

```
         b   b   b   b     b
Given: [ 0 | 1 | 2 | ... | N - 1 ]

bit(0)=0 --> (A) length fits in 1 byte, with a max value (N) of (2^7)-1 (127 Bytes)
bit(0)=1 -+-> bit(1)=0 --> (B) length fits in 2 bytes, with a max value (N) of (2^14)-1 (16+ KB)
          |
          +-> bit(1)=1 -+-> bit(2)=0 --> (C) length fits in 3 bytes, with a max value (N) of (2^21)-1 (2+ MB)
                        |
                        +-> bit(2)=1 --> (D) length fits in 4 bytes, with a max value (N) of (2^29)-1 (536+ MB)
```

As you can see, given this scheme, we allow for a dynamic-sized slice, using only as much bytes as required. It does make trade-offs, such as for example having to use 2 bytes for lengths above 127, even though you would expect that might still fit in 1 byte. However this is OK, as most slices have less than 127 elements (if not all), and even if not, 2 bytes is still a 6 bytes save over the Rivine-encoded slices.

Relevant Go unit tests:
- tests the byte length of a slice encoded length: <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/encoding/slice_test.go#L242-L295>;
- <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/encoding/prefix_test.go#L19-L67> (a unit test taken over from the original rivine encoding library, which itself is taken from the Sia encoding lib, not sure if useful, but relevant none the less);

There is not much more testing for the slices, as the most crucial part is the length, if you can encode/decode the length, the elements is easy, given that the elements are encoded/decoded using the encoding/decoding logic defined by those types.

#### Examples

The nil slice:

```hex
0x00
```

A slice of 3 uint8 integers: `[1, 2, 3]`

```hex
0x06010203
```

All slices in the new 3bot transaction versions are encoded using this scheme.

### Crypto Public Key

A public key consists of a byte slice and an algorithm specifier. The length of the byte slices was encoded as a prefix of the actual byte slice (as already discussed in previous chapter), and the algorithm was specified using a 16-byte fixed char-byte specifier. Giving a total waste of 23 bytes:

+ 8 bytes because of the length: we do not require the length, as in the crypto world, these fixed-byte keys are defined (in size) by the algorithm type (in specific), and thus knowing the algorithm type should be enough to know what amount of bytes to expect;
+ 16 bytes for a specifier for which 1 byte is sufficient. 1 byte would allow us to have 256 unique combinations, which are a lot of different crypto-signature algorithms that can be supported, more than I expect we'll ever need in the lifetime of this chain;

Using this knowledge we have the following 1-byte algorithm specifiers to indicate the (signature) algorithms supported by tfchain:

+ `0x00`: SignatureAlgoEd25519, byte slice is 32 bytes, giving a total of 33 bytes for a Ed25519 pub key;

The algorithm specifier byte is prefixed before the actual key byte slice, when encoding. This way the decoder can decode just the algorithm first to know how many bytes to decode afterwards.

Relevant Go Unit Tests: <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/types/signatures_test.go#L121-L186>;

### Network Addresses

Network addresses are new as part of tfchain Transactions, as the 3bot Transaction versions are the first one to contain a network address type. All network addresses are prefixed with a single byte, indicating both its type and the length.

```
[ type+length | address ] parts/descriptions
| 0                    | 1 | ... | n | byte position

where the first byte has the following layout:

[ type        | length   ]
| 0 | ... | 2 | 3 | ... | 7 |
```

As can be seen, the type is stored in the first 2 bits of the first byte,
and can be any of the following values:

+ `0 0`: `HostName`, length is in the inclusive range of `[1,63]` and the bytes are the raw characters representing the hostname;
+ `1 0`: `IPv4`, length is fixed 4 bytes, the address being the IPv4 address directly as those 4 bytes;
+ `1 1`: `IPv6`, length is fixed 16 bytes, the address being the IPv6 address directly as those 16 bytes;

Relevant Go Unit Tests:
- <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/types/net_test.go#L45-L72>;
- <https://github.com/threefoldfoundation/tfchain/blob/3ac8b1af2f2c130cd24830f884887f7e63453224/pkg/types/net_test.go#L30-L43> (not sure if relevant, depends on your implementation, but for Go we store the addresses as raw byte slices, thus the stringification does require a bit of testing on our side);

Examples:

+ "127.0.0.1": `0x117f000001`;
+ "network.address.com": `0x4c6e6574776f726b2e616464726573732e636f6d`;
+ "2001:db8:85a3::8a2e:370:7334": `0x4220010db885a3000000008a2e03707334`;

**Comment by ahussein** [comment]
https://github.com/threefoldtech/jumpscale_lib/pull/205
the above PR covers encoding of integers and slices as primitive types. For Public Keys and Network addresses these will be objects in the new transaction type that they need to implement the binary property and use the encoding primitives to encode their content
