### ISSUE TITLE
Adding 2 configs to VM with same path result in one config (last one)

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#188]
#### Installation information

- jumpscale version: development
- jumpscale_lib: commit ea4504efd1755e3f710e0490e963b08ba1a234c8
- operating system: Ubuntu 18

#### Detailed description
1- create vm.
2- add config to vm.
3- add another config with same path.
4- deploy and get vm info.
#### Steps to reproduce
```
vm = node_sal.primitives.create_virtual_machine('test_vm', type_='ubuntu:16.04') 
vm.configs.add(name='test', path='/root/test_file.txt', content='this is a test line')
vm.configs.add(name='test2', path='/root/test_file.txt', content='this is another test line')
vm.deploy()
vm.info
```
### Actual Result
Adding two configs on the same path result in one config (last one).
the second config overwrites the first one.
#### if the file is already exist on same path, should it (overwrite or append) the file ?

![image](https://user-images.githubusercontent.com/41957921/46725291-2abf6f00-cc7c-11e8-9e84-66d66634da3b.png)

**Comment by serboctor** [comment]
The `config` doesn't append values, it overwrites, that's the normal and expected behavior.
