### ISSUE TITLE
Document rivine client locktime/multisig combination use case

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#20]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/348](), opened by @robvanmieghem*

An example where the rivine client is used  to send coins  to a multisig address ( 2 out of 3) and spendable in 2 hours.
It should also include the spending again.

**Comment by rkhamis** [comment]
*commented by @ahussein
Rivine client does not support Multisig feature yet. There is a storycard for adding support for this in the client be its currently in the roadmap here: https://docs.greenitglobe.com/gig/org_development/issues/89*

**Comment by rkhamis** [comment]
*commented by @ahussein
support for Multisig will be added here: https://github.com/Jumpscale/lib9/issues/353*

**Comment by rkhamis** [comment]
*commented by @ahussein
Documentation can be found [here](https://github.com/Jumpscale/lib9/tree/development/JumpScale9Lib/clients/blockchain/rivine#multisignature-transactions)

@robvanmieghem  Please check and comment if needed.*

**Comment by mohamedgalal99** [comment]
Sending tokens to multiple participants,and withing specific time as shown in this doc 
https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/blockchain/rivine/README.md#multisignature-transactions
