### ISSUE TITLE
Jumpscale Traefik Client

### ISSUE THREAD

**Issue by arahmanhamdy** [threefoldtech/jumpscale_lib#207]
We need to have traefik client to configure domains with backends

Traefik Client:

template: 
```
etcd = "" #the etcd client instance name to be used
```

methods:
- add_rule(rule_name, [list of domains], [list of ips:ports]) // this method can make use of builtin load balance feature in traefik to add multiple backends for the domains
- add_domains_to_rule(rule_name, [domains])
- delete_domains_from_rule(rule_name, [domains])
- add_backends_to_rule(rule_name, [backends])
- delete_backends_from_rule(rule_name, [backends])
- delete_rule(rule_name)

**Comment by zaibon** [comment]
This api is a bit too naive. Let's try to make something a bit more elaborated.

So traefik is used to connect a frontend to a backend by routing traffic using certain rules.
So we have 3 concepts here:
A proxy is composed of
  - frontend
  - backend

Let's define what properties each component have.
- frontend:
  - is composed multiple routing rules. For now we only use the matching rule based on Host
- Backend:
  - endpoint server address
  - load balancing
  - circuit breaker (not needed in first version)

With this in mind I can see an API like this:
```python
class Proxy:
   def __init__(self, etcd_clients, frontends, backends):
     self.etcd_clients = etcd_clients
      self.fontends= frontends
      self.backends = backends

def deploy(self):
   """
    write the requires configuration in etcd
   """
   pass

def delete(self):
   """
  remove configuration from  etcd
   """
    pass
```

```python
class Frontend:

   def __init__(self, rules):
        self.rules = rules

   def add_rules(self, rule):
  def remove(self, rule):
```

```python
class Backend:
   def __init__(self, servers, load_balancing, circuit_breaker):
        self.servers = servers
        self.load_balancing = load_balancing
        self.curcuit_breaker = curcuit_breaker
```

And we could use it like:
```python
rule1 = Rule(host=''mydomain.com")
frontend = Frontend([rule1])
backend = Backend('192.168.1.10:9000', ...)
proxy = Proxy(etcd_client, [frontend], [backend], )
```

**Comment by BolaNasr** [comment]
commit:
at branch : development_simple_traefik
https://github.com/threefoldtech/jumpscale_lib/commit/923c1a8ce72f7fc2fe853da56e0dc285ea488ea9
