### ISSUE TITLE
Bug: ZDB client gives import error

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/jumpscale_lib#223]
Commit on my management system for bancadati, the zdb client still works (is at commit a9e3663a156b81bcf997042e5fa039dfffe1b1a8) 

When I update to latest development, the client doesn't work anymore
![image](https://user-images.githubusercontent.com/23582741/47991801-759d9c80-e0eb-11e8-8b51-fff56c9678b2.png)

jumpscale_core is at commit: threefoldtech/jumpscale_core@b26808a525946a867dcb7b2db1dcb2300dbac1a7

**Comment by BolaNasr** [comment]
it works good
```
In [1]: cl=j.clients.zdb.configure('test', addr='tlre.gig.tech',port='9900')

In [2]: cl.config
Out[2]: 
config:j.clients.zdb:test

    
    addr = 'tlre.gig.tech'
    
    adminsecret_ = ''
    
    encryptionkey_ = ''
    
    mode = 'user'
    
    port = 9900
    
    secrets_ = ''
```
