### ISSUE TITLE
Creating container with zerotier network didn't join the network

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#226]
### Installation information

- jumpscale version: development
- jumpscale_lib: commit 75a74e4a1844ad2ec123d90cf6401446128b29a7
- operating system: Ubuntu 18

### Steps to reproduce
```
node_sal = j.clients.zos.get(data={'host':<node ip>})
cont = node_sal.containers.create(name='cont', flist='https://hub.grid.tf/tf-bootable/ubuntu:16.04.flist', nics=[{'name': 'f963209147', 'type': 'zerotier', 'id': '1d719394048f3525'}])
```
### Actual Result
The conainer didn't join zerotier network.

### Problem
There was no type default network so it couldn't reach the network. and it didn't raise an error.

**Comment by BolaNasr** [comment]
commit : https://github.com/threefoldtech/jumpscale_lib/commit/637329a56a6b8dc7f0f5ad0b41d5a0658cf82008

**Comment by zaibon** [comment]
zerotier itself is having some problem at the moment, so for now just put this to low priority till zerotier behave properly

**Comment by AhmedHanafy725** [comment]
#### Verified on 
commit 2d116f5384f0e1920ff47aaf216d69fc966725f2
