### ISSUE TITLE
agree on a proper (template-based?) json library

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscale_lib#233]
Currently there doesn't seem to be a standard way to use JSON (in JumpScale) AFAIK. I mean I suppose the standard `json` library is the standard, but there is no standard way AFAIK to link a json-structure to a class, such that we can easily go from a class to its JSON structure and backwards.

This leads to weird code in the `tfchain`/`rivine` JS libraries, where our types implement a `json` property (should really be a method, but it is a property as it is) and a `from_dict` method, as to go from a class instance to a json structure and backwards. It is however a very manual way of doing so, forcing code to manually check if a loaded `json` dict has a property (or sub-sub-...-sub property), and if so, assign it, otherwise assign the reasonable type-nil value).

Examples:
* <https://github.com/threefoldtech/jumpscale_lib/blob/4b1142c03c8dd85a2e047ed5a8f04836121508f2/JumpscaleLib/clients/blockchain/rivine/types/transaction.py#L611-L622>;
* <https://github.com/threefoldtech/jumpscale_lib/blob/4b1142c03c8dd85a2e047ed5a8f04836121508f2/JumpscaleLib/clients/blockchain/rivine/types/transaction.py#L629-L638>
* any other type in the `Rivine` JS library that requires JSON encoding/decoding...

It would simplify and clean up parts of the `tfchain`/`rivine` library code a lot if we could somehow couple a class to a JSON structure scheme, and automatically decode/encode from/to JSON using it.

**Comment by zaibon** [comment]
closing since this is not active anymore
