### ISSUE TITLE
opening an existing tfchain wallet results in different addresses

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscale_lib#250]
I do not have much more details at the moment. But it seems that if you have a wallet with for example 2 addresses. You than close the `js shell` and re-open it again. You'll notice that the addresses returned by the wallet are different than prior to restarting the `js shell`.

**Comment by GlenDC** [comment]
Can't seem to reproduce it anymore. Might have been an invalid issue. Or perhaps it is to do with conflicts in how we store the config. We can re-open the issue if it happens again.

**Comment by ahussein** [comment]
This is how the js wallet deals with addresses generation:
- Addresses are not presisted, only the number of addresses to generate
- Everytime the current_balance is called, we check the current addresses and generate 20 more addresses and check them.
- If we find a used addresses from the extra 20 we generate the height index of a used address is used to update the number of addresses to generate when the configurations are loaded
