### ISSUE TITLE
Fix IYO integration to humhub 

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/jumpscale_lib#251]
- humhub admin user can't login after enabling authentication with IYO 

- Enable organization admins to be administrators in humhub

**Comment by ranatrk** [comment]
**ISSUE**: humhub admin user can't login after enabling authentication with IYO

**FIX**: removing the following line from _protected/config/common.php_
```     
'class' => 'yii\authclient\Collection',
```

**Comment by ranatrk** [comment]
**ISSUE:** Enable organization admins to be administrators in humhub
**NO FIX**: The only way found to know if a user is an owner is to make the user grant admin scope which doesn't work.

**Comment by PeterNashaat** [comment]
#### verified
humhub admin user can login after adding IYO integration
