### ISSUE TITLE
Failed to create zerodb server on kristof-farm

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_lib#255]
#### Installation information

- jumpscale version: development
- jumpscale lib: commit bb3e1ee3bbbef46446279f9796b05d6698de64c5

### Detailed description
1- create zdb on [kristof-farm](https://capacity.threefoldtoken.com/?cru=0&mru=0&farmer=kristof-farm&country=&hru=0&sru=0&page=1) 

### Steps to reproduce
```
node_sal = j.clients.zos.get('test_node', data={'host':'10.102.114.69'})
zdb = node_sal.primitives.create_zerodb('test_zdb', path='/mnt/storagepools/674e0814-23c3-455f-a583-dc6c56455dad/filesystems/zdb', mode='user', node_port=8050)
zdb.deploy()
```

### Actual Result
This is happening in the most nodes of kristof-farm 

![image](https://user-images.githubusercontent.com/41957921/48897882-fa124e00-ee53-11e8-9082-a407bf8426f7.png)

**Comment by muhamadazmy** [comment]
Questions:
- does this happen only on kds-farm ? this specific node ?
- do we ever need to create zdbs manually ?
- can we get the zdb log, see exactly why the process exit ?
- are u sure no other zdb is using the same namespace ?

**Comment by muhamadazmy** [comment]
Questions:
- does this happen only on kds-farm ? this specific node ?
- do we ever need to create zdbs manually ?
- can we get the zdb log, see exactly why the process exi

**Comment by zaibon** [comment]
closed for inactivity
