### ISSUE TITLE
Implement an RPC server for atomicswap

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#26]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/341](), opened by @ahussein*

Our current atomicswap SAL is not decentralized. It depends on the node that is running the SAL to orchestrate the communication between the two atomicswap parties.

We need develop an RPC server that implement the atomicswap interface:
- Initiate
- Participate
- Audit
- Redeem
- Refund

The server that can be used as an initiator/participant in the atomicswap process.  More details about the APIs can be found [here](https://github.com/Jumpscale/lib9/tree/development/JumpScale9Lib/tools/atomicswap#atomicswap-apis)

The APIs should relay the actual work to the light wallet of the corresponding cryptocurrency. No Full node is assumed to be running on any of the nodes.

Jimber already did some effort to implement a similar RPC server but they were running full nodes, but the APIs should be similar to theirs, their code base can be found [here](https://github.com/rivine/AtomicExchange.Scripts/tree/72bf39f324fab984698539ab8a4b7e12f945a680)

**Requirements** 
- Well structured code
- Unit tests
- Work on branch
- Create PR and code review should be performed

**Comment by rkhamis** [comment]
*commented by @despiegk
should not be done this way, there is an orderbook server which needs to be used*

**Comment by rkhamis** [comment]
*commented by @ahussein
This layer should be used by the order book. This will use light wallets and not full nodes.*

**Comment by ahussein** [comment]
why this is closed ?

**Comment by despiegk** [comment]
please link to new location in threefold tech & we need to discuss how to go forward, lets first finish the DM server

**Comment by despiegk** [comment]
input kristof required, first need DM in usable state

**Comment by rkhamis** [comment]
Digital Me is development ready. Will close this as this is no longer needed
