### ISSUE TITLE
jumpscale zbundle is outed 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscale_lib#282]
according to this ticket https://github.com/threefoldtech/support/issues/11
zbundle jumpscale seems to be outed

**Comment by Pishoy** [comment]
@maxux any update about above ?

**Comment by maxux** [comment]
Please try again using this image (it's updated): https://hub.grid.tf/maxux/fullcapacity.flist

**Comment by Pishoy** [comment]
it works thanks
