### ISSUE TITLE
Capacity freeze without any reason

### ISSUE THREAD

**Issue by maxux** [threefoldtech/jumpscale_lib#291]
According to logs, nothing special occures.
Some exceptions are recurrent, we will fix them, but are not related.

Some alternative should be considered, running python h24 for months, in production seems not to be the best approach IMO.

**Comment by zaibon** [comment]
https://github.com/threefoldtech/jumpscale_lib/commit/6908fb5e5b4842bfe9494110b587d004ff7d0145 
Should quite improve things for now.
