### ISSUE TITLE
reserved capacity not shown correct values

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscale_lib#301]
capacity reserved values are not correct in capacity website as below screen shot 
![image](https://user-images.githubusercontent.com/21987477/61223514-12a1e200-a71d-11e9-8c44-fcced6e47926.png)

**Comment by serboctor** [comment]
It is normal that the reserved values are higher than the total. We allow over-reservation.
I'll close the ticket. If you check the reserved templates on this node and find that the numbers are inaccurate, open it again with more info.
