### ISSUE TITLE
Grid capacity: track used capacity 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#38]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/310](), opened by @zaibon*

Currently the capacity tracked is only the raw capacity of the node. We also need to track the different deployed capacity to have a better view on the usage of the grid.

The node robot needs to track
- reserved capacity units
- actual capacity used units
and publish these along with the raw capacity to the central repository.

Besides publishing this every two hours, intermediate updates should also be done when workloads are deployed or removed.

**Comment by rkhamis** [comment]
*commented by @zaibon
Server side have been updated to support tracking of the new metrics. 
Still to do:
- update [capacity SAL](https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/zero_os/sal/Capacity.py) to allow to pass these metrics in the registration
- update the template to use the new methos of the sal to register the new metrics*

**Comment by rkhamis** [comment]
*commented by @zaibon
@arahmanhamdy make sure to base your work on : https://github.com/Jumpscale/lib9/pull/323*

**Comment by hossnys** [comment]
Deleting files don't affect used storage values

**Comment by hossnys** [comment]
no update happened to used capacity after deletion of data from the vm disk .

**Comment by zaibon** [comment]
@hossnys this is normal, cause 0-db is an always append data store. which means as long as you don't run compactation, you will never see storage decreased even if you delete files.
