### ISSUE TITLE
Local discovery of other blockchain nodes

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#48]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/264](), opened by @FastGeert*

Need an extra method in the zero-os tfchainc sal to discover other tfchain-daemons running in the same network. 

This issue depends on nmap being available in the tfchain flist. See https://github.com/zero-os/flists/issues/1

**Comment by despiegk** [comment]
why is this needed, what do we try to achieve.
maybe there is a fundamental issue in how we use/deploy our blockchain rivine?
