### ISSUE TITLE
Support for macvlan interface type in zero-os sal for containers

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#52]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/240](), opened by @FastGeert*

See https://github.com/zero-os/0-core/issues/646

**Comment by rkhamis** [comment]
*commented by @despiegk
for what is this needed?*

**Comment by rkhamis** [comment]
*commented by @FastGeert
It will make us able to run the tfchain on the small zero-os nodes in the testlab. Basically the tfchain daemons will be able to connect with each other in a lan context. Currently this fails because their networking setup ommits that.*

**Comment by Pishoy** [comment]
@rkhamis, Please write the verification steps
