### ISSUE TITLE
Finish/Review zrobot SAL

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#57]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/217](), opened by @zaibon*

Need to review and finish if needed the zero-os Zrobot SAL. 
The SAL needs to provide all the method to use the robot as a primitive for 0-OS.
So deploying a robot should be as easy as deploying a container.

Need all method to :
- start 
- stop
- upgrade
- ...

**Comment by despiegk** [comment]
need to understand what needs to be done here
