### ISSUE TITLE
improve getNetworkInfo in nettools

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscale_lib#66]
doesn't work for OSX
also is not clear which format is now used for getnetwork info

![image](https://user-images.githubusercontent.com/6021844/43682665-f17870a4-987b-11e8-9767-a99da0f9d4d9.png)

the parsing seems to be different than what we use

lets test/define

**Comment by despiegk** [comment]
found out we were using other format on prefab
![image](https://user-images.githubusercontent.com/6021844/43683317-3f62999a-9889-11e8-94e6-2a28079ad02b.png)


lets standardise on the prefab one

and std lib should use that one

also check other #TODO in the nettools lib

**Comment by BolaNasr** [comment]
@despiegk 
i can't find the nettools lib..
only nettools i have at core in Threefoldtech repo

**Comment by BolaNasr** [comment]
@despiegk 
can you please provide the mentioned file path ?

**Comment by despiegk** [comment]
see title: improve getNetworkInfo in nettools

nettools is module in js95

**Comment by BolaNasr** [comment]
[PR](https://github.com/threefoldtech/jumpscale_prefab/pull/23)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/43820421-852d7ddc-9ae6-11e8-91da-183a59a15e89.png)

doesnt work for me?

**Comment by despiegk** [comment]
please fix directly on development branch and let despiegk known when done

**Comment by despiegk** [comment]
test on osx too
make sure works for ipv6/4

**Comment by BolaNasr** [comment]
@despiegk 

those my commits : 

https://github.com/threefoldtech/jumpscale_core/commit/70376e604e85bb1b3a823aa225427f61bbdaeb90

https://github.com/threefoldtech/jumpscale_prefab/commit/1574a75cd680301e82360a91e97c93a154f5405e

**Comment by BolaNasr** [comment]
@despiegk 
Those my commits
https://github.com/threefoldtech/jumpscale_core/commit/70376e604e85bb1b3a823aa225427f61bbdaeb90

https://github.com/threefoldtech/jumpscale_prefab/commit/1574a75cd680301e82360a91e97c93a154f5405e

**Comment by Dina-Abd-Elrahman** [comment]
- verification steps:
 
j.sal.nettools.checkIpAddressIsLocal 5ed143b68f4f670f95db63370de152d2ecfa7028 working on both macOS and linux 

j.sal.nettools.checkUrlReachable working on both macOS and linux 

j.sal.nettools.checkListenPort doesn't work in both mac and linux 

![error](https://user-images.githubusercontent.com/21218053/44031079-234e866c-9f03-11e8-901d-117b4285b927.jpg)

**Comment by BolaNasr** [comment]
@Dina-Abd-Elrahman 
i fix this Error : 
my commit : https://github.com/threefoldtech/jumpscale_core/commit/f182ac37b4a284361615fb5372389967b82af1fa

**Comment by Dina-Abd-Elrahman** [comment]
## verification steps:

j.sal.nettools.commit
j.sal.nettools.getDefaultIPConfig
j.sal.nettools.getDefaultRouter
j.sal.nettools.getHostname
j.sal.nettools.getIpAddress
j.sal.nettools.getIpAddresses
j.sal.nettools.getMacAddress
j.sal.nettools.getMacAddressForIp
j.sal.nettools.getNameServer
j.sal.nettools.getNetworkInfo
j.sal.nettools.getNics
j.sal.nettools.getNicType
j.sal.nettools.getVlanTag
j.sal.nettools.getVlanTagFromInterface
j.sal.nettools.ip_to_num
j.sal.nettools.ipSet
j.sal.nettools.isNicConnected
j.sal.nettools.logger
j.sal.nettools.logger_enable 
j.sal.nettools.pingMachine
j.sal.nettools.validateIpAddress
j.sal.nettools.waitConnectionTest

for both mac and linux 

## Error:
![ff](https://user-images.githubusercontent.com/21218053/44098609-ee732f40-9fe0-11e8-9b6c-7529ba5c630f.png)

![error](https://user-images.githubusercontent.com/21218053/44098766-500ef63a-9fe1-11e8-9900-f8a9d93456a6.png)

## Jumpscale version:
core --> efed99e24424a3bc50d1b347b2229a5adcd7bd2b
lib --> 50f225b5eb07f31275b7c1c08bc33f8a4b789005
prefab --> 1574a75cd680301e82360a91e97c93a154f5405e

**Comment by BolaNasr** [comment]
@Dina-Abd-Elrahman 
this commit https://github.com/threefoldtech/jumpscale_core/commit/199d7a77089c9cc835e0c906e894c063080ead41
fix those errors and another errors 
at second command must be post as int not string

**Comment by Dina-Abd-Elrahman** [comment]
## verification steps:

j.sal.nettools.bridgeExists
j.sal.nettools.downloadIfNonExistent
j.sal.nettools.getDomainName
j.sal.nettools.getHostByName
j.sal.nettools.download
j.sal.nettools.getReachableIpAddress
j.sal.nettools.isIpInDifferentNetwork
j.sal.nettools.isIpLocal
j.sal.nettools.tcpPortConnectionTest
j.sal.nettools.waitConnectionTestStopped
j.sal.nettools.pm_formatMacAddress


## Jumpscale version: 

core --> 140bfeaf59ffd832be441afeaed460d830050b5e
lib --> 0de43602a27f373b4e0ee8614c5b30ed21522335
prefab --> 970df5cf06bb0b1afbb1d3b164d434794022d06d

tested for both mac OS and Linux
