### ISSUE TITLE
zerostor client using golang zero-stor client

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscale_lib#67]
The digital me needs to be able to read/write to zero-stor backend.

This is an important feature for storing bigger files or tlogs.

For that we need a CLIENT which interacts with the z-stor golang client which then runs as daemon, I believe we use GRPC to instruct the daemon?

Create some test script as part of client implementation.
also make sure prefab exists to install/start the zero-stor client as daemon

on osx/linux

**Comment by zaibon** [comment]
I've looked a bit into this. Seems we still don't have a proper solution for the metadata of 0-stor. as far as I know etc is still required. So it seems some work there need to be done on 0-stor if we want to use it without etcd.

**Comment by despiegk** [comment]
needs to work without ETCD
the client is responsible to maintain the metadata
