### ISSUE TITLE
Zboot parsing fails

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/jumpscale_lib#68]
Zboot client broken after these changes https://github.com/threefoldtech/jumpscale_lib/commit/b9c116620bef0bdd9af1fd59a06a6f88c6968602

![image](https://user-images.githubusercontent.com/23582741/43722497-b0866388-9995-11e8-865a-1a23814dcaae.png)

This still works on the client before the fork

**Comment by islamTaha12** [comment]
this commit should fix it
https://github.com/threefoldtech/jumpscale_lib/commit/3604befef959f27b83ac1fa59ced04c4aeafdcb7
