### ISSUE TITLE
setup.py forces requirement of pip3 (installs electrum in non-standard way)

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_lib#70]
the forced installation of electrum (without checking if it already exists) at line 18 in setup.py by using pip3 unconditionally forces pip3 to become a critical build dependency.  this needs to be removed or at least replaced with a detection of whether electrum has already been installed.

**Comment by delandtj** [comment]
[x.txt](https://github.com/threefoldtech/jumpscale_lib/files/2269586/x.txt)

**Comment by delandtj** [comment]
why is electrum 3.2.2 - a cryptocurrency wallet - a critical hard dependency of jumpscale_lib?

**Comment by ahussein** [comment]
It is used as an embedded library to be used as a client for electrum daemon.
