### ISSUE TITLE
Move  j.clients.blockchain.Electrum to j. clients.blockchain.btc.Electrum

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscale_lib#82]
This would make it clear that it is a Bitcoin client

**Comment by ahussein** [comment]
There is a problem with the current behavior of js when trying to have sub-namespace. I am currently trying to move j.clients.rivine to j.clients.blockchain.rivine and it is not working as expected. Still investigating it..

**Comment by ahussein** [comment]
Since we have a limitation in js that hooks can only be 3 levels, we will fix the hook to be:
j.clients.btc_electrum

**Comment by ahussein** [comment]
fixed by 64df6f2
