### ISSUE TITLE
Different generated  address handling for the tfchain client 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscale_lib#88]
By default only generate 1 address
When doing a balance check, check for 10 more addresses and update the counter when 1 is used, repeat until no used addresses found.
## motivation
Most people will only use 1 address
This will facilitate the restore of a wallet as you no longer need to know the amount of addresses previously generated

**Comment by ahussein** [comment]
fixed by: https://github.com/threefoldtech/jumpscale_lib/pull/168

**Comment by ahussein** [comment]
Comments from @robvanmieghem 
```
 generate_address  calls  _generate_spendable_key which calls generate_address and for every key, an explicit call is made to the explorer, while it’s done again to check the balance, 
Also what happens if two jumpscale clients operate at the same time, as for address in unused_addresses: del self._keys[address] will make it invisible until a new wallet instance is made?

Can’t we make it simpler by not mixing and storing temporary data in non temporary instance properties ?
```

- _generate_spendable_key does not call generate_address, where do you see that ?
- calls to the explorer only happen when checking balance, when generating the address we do not check the explorer, where do you see that ?
- As I mentioned in telegram chat, js is not intended to be used in multithreaded environment, so no two instances would be running on the same time.
- Unused address will be checked again everytime current_balance is called, so no need to create a new instance.

I agree that the code can be simpler and the mixing between storing temporary data in non temporary instance properties, I will check that.

**Comment by ahussein** [comment]
PR: https://github.com/threefoldtech/jumpscale_lib/pull/176
