### ISSUE TITLE
finish builder for ZOS/Containers & JUMPSCALE

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscale_lib#92]
#### Installation information

- jumpscale version: development branch
- operating system: linux & OSX (TEST ON BOTH)

#### ON LINUX

```
js_shell 'j.tools.builder.test()'
```

will create a virtualbox machine, download ZOS, create container, do some builds

there is still something wrong with the build location to do the packaging
there are some todo's in the code

#### ON OSX

sanbox locally
```
js_shell 'j.tools.sandboxer.python.do(build=True)'
```

will build python & jumpscale & package

the virtualbox test (first do on linux so we know it works in general)
```
js_shell 'j.tools.builder.test()'
```

#### TODO

- test correct behavior
- do all fixes on development_builder (so I can review pull request)

**Comment by BolaNasr** [comment]
git pull ( jumpscale_core, jumpscale_lib, jumpscale_prefab) from development_builder branch
and git pull DIgitalMe at this commit (https://github.com/threefoldtech/digital_me/commit/75b379c33784bde4d59f539bfe35e7739da31ea9)

**Comment by hossnys** [comment]
verified on :
branch development_builder
and on DigitalMe commit [75b379c](https://github.com/threefoldtech/digital_me/commit/73c684c623459cb70a30cf009f28e2932b37fd6d)
on operating system: linux ubuntu 16.04& OSX

**Comment by hossnys** [comment]
verfied on : 
branch development
and on DigitalMe commit [75b379c](https://github.com/threefoldtech/digital_me/commit/75b379c33784bde4d59f539bfe35e7739da31ea9)
on operating system: linux ubuntu 16.04& OSX
